version: "3.4"

services: 
  bot:
    build: .
    links: 
      - database
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
  database:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: keko


