version: "3.5"

services: 
  bot:
    build: .
    restart: unless-stopped
    container_name: roboduck_bot
    links:
      - postgres
    depends_on: 
      - postgres
    environment: 
      DB_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_USER}"
    
  postgres:
    image: postgres:13
    restart: unless-stopped
    container_name: roboduck_db
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
    environment: 
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432

volumes:
  postgres_data:

